antife/Mityba/urls.py
from django.urls import path
from . import views

app_name = 'Mityba'

urlpatterns = [
    # Define your URL patterns here
    path('product/', views.product, name='product'),
    path('receptai_list/', views.receptai_list, name='receptai_list'),
    path('create_recipe/', views.create_recipe_view, name='create_recipe'),
    path('valgiarastis-analysis/', views.valgiarastisAny, name='valgiarastisAnalysis'),  # Change the URL pattern and view name
    path('valgiarastis/', views.valgiarastis, name='valgiarastis'),  # Move this URL pattern to below the valgiarastisAny pattern
    path('create_valgiarastis/', views.create_valgiarastis, name='create_valgiarastis'),
    path('receptai_list/<int:recipe_id>/', views.remove_recipe_view, name='remove_recipe'),
    path('valgymai/', views.valgymai_open, name='valgymai_open'),
    path('manoreceptai_list/', views.manoreceptai_list, name='manoreceptai_list'),
    path('add_to_favorites/<int:recipe_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('delete_valgomasReceptas/<int:valgymo_receptas_id>/', views.delete_valgomasReceptas, name='delete_valgomasReceptas'),
    path('delete_valgomasProduktas/<int:valgomas_produktas_id>/', views.delete_valgomasProduktas, name='delete_valgomasProduktas'),
    path('add_valgymas/', views.add_new_valgymas, name='add_valgymas'),
    path('saveCopy/', views.saveCopy, name='saveCopy'),
    path('copyValgiarastis/', views.copyValgiarastis, name='copyValgiarastis'),
    path('receptukurimas/', views.create_recipe_view, name='create_recipe'),
    path('panaudotireceptai/', views.panaudotireceptai, name='panaudoti_receptai'),
    path('receptai_list/<int:recipe_id>/edit/', views.edit_recipe, name='edit_recipe'),
    path('rekomendacijos/', views.rekomendacijos, name='rekomendacijos'),
    path('receptai_listt/<int:recipe_id>/', views.toggle_recipe_visibility, name='toggle_recipe_visibility'),
    path('generate-recommendations/', views.generate_recommendations_view, name='generate_recommendations'),
    path('edit_valgomasReceptas/', views.edit_valgomasReceptas, name='edit_valgomasReceptas'),
    path('edit_valgomasProduktas/', views.edit_valgomasProduktas, name='edit_valgomasProduktas'),
]

antife/Profilis/urls.py
from django.urls import path
from . import views

app_name = 'profilis'

urlpatterns = [
    path('', views.profilisview, name='profilisview'),
    path('save_profile_changes/', views.save_profile_changes, name='save_profile_changes'),
    path('profilis/', views.profilisview, name='profilis'), 
]

antife/antife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls"))
]

antife/Profilis/models.py
from django.db import models

# Create your models here.

antife/Profilis/views.py
from homepage.models import Naudotojai
from django.utils import formats
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import redirect
import re
from django.urls import reverse
from datetime import datetime
from django.shortcuts import render

def profilisview(request):
    user_id = None
    username = None
    vardas = None
    pavarde = None
    telefonas = None
    gimimo_Data = None
    el_pastas = None
    password = None
    form_submitted = False  # Initialize form_submitted to False

    if request.user.is_authenticated:
        user_id = request.user.id
        username = request.user.username
        el_pastas = request.user.email
        password = request.user.password
        try:
            # Retrieve the latest data from the database
            naudotojas = Naudotojai.objects.get(user=request.user)
            vardas = naudotojas.vardas
            pavarde = naudotojas.pavarde
            telefonas = naudotojas.telefonas
            gimimo_Data = naudotojas.gimimo_data
        except Naudotojai.DoesNotExist:
            # Handle the case where there's no related Naudotojai instance for the current user
            pass
    formatted_gimimo_Data = formats.date_format(gimimo_Data, "Y-m-d") if gimimo_Data else ""
    context = {
        'user_id': user_id,
        'username': username,
        'password': password,
        'vardas': vardas,
        'pavarde': pavarde,
        'telefonas': telefonas,
        'gimimo_Data': formatted_gimimo_Data,
        'el_pastas': el_pastas,
        'form_submitted': form_submitted,  # Pass form_submitted to the template
    }
    
    # Clear any existing messages
    storage = messages.get_messages(request)
    storage.used = True

    return render(request, 'Profilis.html', context)


from django.contrib import messages

def save_profile_changes(request):
    if request.method == 'POST':
        # Retrieve form data from the request
        username = request.POST.get('username')
        vardas = request.POST.get('vardas')
        pavarde = request.POST.get('pavarde')
        telefonas = request.POST.get('telefonas')
        gimimo_data = request.POST.get('birthday')  # Get the date string from the form
        el_pastas = request.POST.get('el_pastas')

        # Retrieve the user's profile from the database
        naudotojas = Naudotojai.objects.get(user=request.user)

        error_messages = []  # Initialize a list to store error messages

        # Update the user's email
        if el_pastas:
            if not re.match(r"[^@]+@[^@]+\.[^@]+", el_pastas) or not el_pastas.endswith('@gmail.com'):
                error_messages.append('Neteisingai įvestas elektronins paštas. Įveskite teisingą naudodami @gmail.com')
            else:
                request.user.email = el_pastas
                request.user.save()

        # Validate and update other fields
        if gimimo_data:
            try:
                birthdate_obj = datetime.strptime(gimimo_data, '%Y-%m-%d').date()
                today = datetime.now().date()
                if birthdate_obj >= today:
                    raise ValueError  # Birthdate should be in the past
            except ValueError:
                error_messages.append('Neteisinga gimimo data. Pasirinkite dar kartą.')
            else:
                naudotojas.gimimo_data = gimimo_data

        if vardas:
            naudotojas.vardas = vardas
        if pavarde:
            naudotojas.pavarde = pavarde
        if telefonas:
            if not re.match(r"\+370\d{8}$", telefonas):
                error_messages.append('Neteisingai įvestas telefono numeris.  Įveskite iš naujo naudodami prefiksą +370')
            else:
                naudotojas.telefonas = telefonas
        if el_pastas:
            naudotojas.el_pastas = el_pastas
        if username:
            if User.objects.filter(username=username).exclude(pk=request.user.pk).exists():
                error_messages.append('Šis slapyvardis jau užimtas')
            else:
                request.user.username = username
                request.user.save()

        # Save the updated profile if there are no error messages
        if not error_messages:
            try:
                naudotojas.save()
                messages.success(request, 'Profilis sėkmingai atnaujintas')
                # Redirect the user to the profile page or any other page as needed
                return redirect('profilis:profilisview')
            except Exception as e:
                error_messages.append(f'Klaida atnaujinant profilį: {str(e)}')

        # If there are error messages, add them to the messages framework
        for message in error_messages:
            messages.error(request, message)

        # Redirect back to the editing page with error messages
        return redirect(reverse('profilis:profilisview'))

antife/Profilis/templates/Profilis.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Profilis
{% endblock %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'styles/errors.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/profile.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<div class="container">
    <div class="header">
        <h1>Profilio informacija</h1>
        <!-- Button to toggle edit mode -->
        <button type="button" class="btn btn-primary custom-button" id="editProfileBtn">Redaguoti</button>
    </div>
    
    {% if messages %}
        <div class="error-container">
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% elif message.tags == 'success' %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="profile-info" id="profileInfoContainer">
        <div class="profile-info-item">
            <p>Unikalus numeris: {{ user_id|default:"Nepasiekiamas" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Slapyvardis: {{ username|default:"Nepasiekiamas" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Vardas: {{ vardas|default:"Nepasiekiamas" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Pavardė: {{ pavarde|default:"Nepasiekiama" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Telefono numeris: {{ telefonas|default:"Nepasiekiamas" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Gimimo data: {{ gimimo_Data|default:"Nepasiekiama" }}</p>
        </div>
        <div class="profile-info-item">
            <p>Elektroninis paštas: {{ el_pastas|default:"Nepasiekiamas" }}</p>
        </div>
    </div>

    <!-- Editing form (initially hidden) -->
    <form id="editProfileForm" style="display: none;" action="{% url 'profilis:save_profile_changes' %}" method="post">
        {% csrf_token %}
        <div class="profile-info-item">
            <label for="username">Slapyvardis:</label>
            <input type="text" id="username" name="username" value="{{ username }}">
        </div>
        <div class="profile-info-item">
            <label for="vardas">Vardas:</label>
            <input type="text" id="vardas" name="vardas" value="{{ vardas }}">
        </div>
        <div class="profile-info-item">
            <label for="pavarde">Pavardė:</label>
            <input type="text" id="pavarde" name="pavarde" value="{{ pavarde }}">
        </div>
        <div class="profile-info-item">
            <label for="telefonas">Telefono numeris:</label>
            <input type="text" id="telefonas" name="telefonas" value="{{ telefonas }}">
        </div>
        <div class="profile-info-item">
            <label for="gimimo_Data">Gimimo data:</label>
            <input type="date" id="gimimo_Data" name="gimimo_Data" value="{{ gimimo_Data }}">
        </div>
        <div class="profile-info-item">
            <label for="el_pastas">Elektroninis paštas:</label>
            <input type="text" id="el_pastas" name="el_pastas" value="{{ el_pastas }}">
        </div>
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary">Išsaugoti</button>
    </form>
</div>

<script>
    document.getElementById("editProfileBtn").addEventListener("click", function() {
        // Toggle visibility of the editing form
        var editProfileForm = document.getElementById("editProfileForm");
        var profileInfoContainer = document.getElementById("profileInfoContainer");
        editProfileForm.style.display = editProfileForm.style.display === "none" ? "block" : "none";
        profileInfoContainer.style.display = profileInfoContainer.style.display === "none" ? "block" : "none";

        // Set the value of the date input field to the current gimimo_Data
        var gimimo_Data = "{{ gimimo_Data }}";  
        var birthdayInput = document.getElementById("gimimo_Data");
        if (gimimo_Data && gimimo_Data !== 'None') {
            birthdayInput.value = gimimo_Data;
        }
    });
</script>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-image: url("{% static 'images/profileback2.png' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        background-color: rgba(255, 255, 255, 0.8); /* White with 80% opacity */
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .profile-info-item {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .profile-info-item label {
        flex: 0 0 150px;
        font-weight: bold;
    }

    .profile-info-item input[type="text"],
    .profile-info-item input[type="date"] {
        flex: 1;
        padding: 8px;
        margin-left: 10px;
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .btn-primary {
        background-color: #3498db;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-primary:hover {
        background-color: #2980b9;
    }

    .custom-button {
        background-color: #3498db;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .custom-button:hover {
        background-color: #2980b9;
    }

    .alert {
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 4px;
    }

    .alert-danger {
        background-color: #f8d7da;
        color: #721c24;
    }

    .alert-success {
        background-color: #d4edda;
        color: #155724;
    }
</style>

{% endblock %}