antife/Mityba/urls.py
from django.urls import path
from . import views

app_name = 'Mityba'

urlpatterns = [
    # Define your URL patterns here
    path('product/', views.product, name='product'),
    path('receptai_list/', views.receptai_list, name='receptai_list'),
    path('create_recipe/', views.create_recipe_view, name='create_recipe'),
    path('valgiarastis-analysis/', views.valgiarastisAny, name='valgiarastisAnalysis'),  # Change the URL pattern and view name
    path('valgiarastis/', views.valgiarastis, name='valgiarastis'),  # Move this URL pattern to below the valgiarastisAny pattern
    path('create_valgiarastis/', views.create_valgiarastis, name='create_valgiarastis'),
    path('receptai_list/<int:recipe_id>/', views.remove_recipe_view, name='remove_recipe'),
    path('valgymai/', views.valgymai_open, name='valgymai_open'),
    path('manoreceptai_list/', views.manoreceptai_list, name='manoreceptai_list'),
    path('add_to_favorites/<int:recipe_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('delete_valgomasReceptas/<int:valgymo_receptas_id>/', views.delete_valgomasReceptas, name='delete_valgomasReceptas'),
    path('delete_valgomasProduktas/<int:valgomas_produktas_id>/', views.delete_valgomasProduktas, name='delete_valgomasProduktas'),
    path('add_valgymas/', views.add_new_valgymas, name='add_valgymas'),
    path('saveCopy/', views.saveCopy, name='saveCopy'),
    path('copyValgiarastis/', views.copyValgiarastis, name='copyValgiarastis'),
    path('receptukurimas/', views.create_recipe_view, name='create_recipe'),
    path('panaudotireceptai/', views.panaudotireceptai, name='panaudoti_receptai'),
    path('receptai_list/<int:recipe_id>/edit/', views.edit_recipe, name='edit_recipe'),
    path('rekomendacijos/', views.rekomendacijos, name='rekomendacijos'),
    path('receptai_listt/<int:recipe_id>/', views.toggle_recipe_visibility, name='toggle_recipe_visibility'),
    path('generate-recommendations/', views.generate_recommendations_view, name='generate_recommendations'),
    path('edit_valgomasReceptas/', views.edit_valgomasReceptas, name='edit_valgomasReceptas'),
    path('edit_valgomasProduktas/', views.edit_valgomasProduktas, name='edit_valgomasProduktas'),
]

antife/antife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls"))
]

antife/homepage/urls.py
from django.urls import path, include
from .views import home, login, register, logout_view, loged

urlpatterns = [
   path("", home, name="home"),
   path('login/', login, name='login'),
   path('register/', register, name='register'),
   path('logout/', logout_view, name='logout'),
   path('mityba/', include('Mityba.urls', namespace='mityba')),
   path('forumas/', include('Forumas.urls', namespace='forumas')),
   path('profilis/', include('Profilis.urls', namespace='profilis')), 
   path('kraujo_tyrimai/', include('Kraujo_tyrimai.urls', namespace='kraujo_tyrimai')), 
    path('baseLogged/', loged, name='loged'),
]

antife/Mityba/models.py
from django.db import models

# Create your models here.

antife/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    calories = models.DecimalField(max_digits=6, decimal_places=2)
    total_fat = models.DecimalField(max_digits=5, decimal_places=2)
    fiber = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    phenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    measure = models.CharField(max_length=255)
    homePhenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    homeWeight = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.CharField(max_length=255)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Naudotojai(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    vardas = models.CharField(max_length=255)
    pavarde = models.CharField(max_length=255)
    telefonas = models.CharField(max_length=255)
    el_pastas = models.CharField(max_length=255)
    gimimo_data = models.DateField()
    level = models.IntegerField()
    last_login = models.DateTimeField(null=True, blank=True)

class Receptai(models.Model):
    kalorijos = models.FloatField(default=0.0)
    pavadinimas = models.CharField(max_length=255)
    fenilalaninas = models.FloatField(default=0.0)
    baltymai = models.FloatField(default=0.0)
    aprasas = models.CharField(max_length=300)
    visible = models.BooleanField(default=True)

class Irasai(models.Model):
    pavadinimas = models.CharField(max_length=255, default="Pavadinimas")
    tekstas = models.CharField(max_length=2555)
    data = models.DateField()
    category = models.CharField(max_length=50,default="Daktarui") # New field for category
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Kraujo_tyrimai(models.Model):
    data = models.DateField()
    fenilalaninas = models.IntegerField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Naudotojo_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Megstamiausi_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Valgiarasciai(models.Model):
    diena = models.IntegerField()
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    data = models.DateField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Komentarai(models.Model):
    tekstas = models.CharField(max_length=255)
    data = models.DateField()
    fk_Irasasid_Irasas = models.ForeignKey(Irasai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)
    likes = models.ManyToManyField(Naudotojai, related_name='liked_comments', blank=True)

class Valgymai(models.Model):
    tipas = models.CharField(max_length=255)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    fk_Valgiarastisid_Valgiarastis = models.ForeignKey(Valgiarasciai, on_delete=models.CASCADE)


class Valgomas_produktas(models.Model):
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Valgymo_receptas(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Recepto_produktai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

antife/Mityba/views.py
import os
import random
from django.conf import settings
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from homepage.models import Product, Receptai, Kraujo_tyrimai, Naudotojai, Valgymai, Valgiarasciai, Recepto_produktai, Naudotojo_receptai, Megstamiausi_receptai, Valgymo_receptas, Valgomas_produktas
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q, F, Case, Value, When, Count
from django.contrib.auth import authenticate
from django.contrib import messages
from django.http import JsonResponse
from django import forms
from .forms import ValgymasForm
from decimal import Decimal
from django.core.serializers import serialize
import json
import logging, webbrowser
from django.urls import reverse
from django.db.models import Exists, OuterRef
from django.db import models


logger = logging.getLogger(__name__)

def panaudotireceptai(request):
    # Get the count of each recipe used in Valgymo_receptas
    recipe_counts = Valgymo_receptas.objects.values('fk_Receptasid_Receptas__pavadinimas').annotate(count=Count('fk_Receptasid_Receptas__pavadinimas'))

    # Convert queryset to list of dictionaries
    recipe_counts_list = list(recipe_counts.values('fk_Receptasid_Receptas__pavadinimas', 'count'))

    return render(request, 'PanaudotiReceptai.html', {'recipe_counts': recipe_counts_list})

def valgiarastis(request):
  naudotojas = Naudotojai.objects.get(user=request.user)
  valgiarasciai = Valgiarasciai.objects.filter(fk_Naudotojasid_Naudotojas=naudotojas)
  valgiarasciai_json = serialize('json', valgiarasciai)
  context = {'valgiarasciai_json': valgiarasciai_json}
  return render(request, 'valgiarastis.html', context)

from django.utils import timezone
import math
from django.shortcuts import render
from django.db.models import F
from django.core import serializers
from django.db.models.functions import Abs
from django.db.models import ExpressionWrapper, IntegerField
from django.db.models import ExpressionWrapper, F, IntegerField, Func
from datetime import datetime
from django.db.models import Min
from datetime import datetime
from django.db.models import Min, ExpressionWrapper, F, DurationField


import openpyxl
import pandas as pd
from django.http import JsonResponse

from django.views.decorators.csrf import csrf_exempt
from django.core.management import call_command
from io import StringIO
import json

@csrf_exempt
def generate_recommendations_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        bendras_baltymas = data.get('bendras_baltymas')
        bendras_fenilalaninas = data.get('bendras_fenilalaninas')
        
        # Call the management command and pass the variables
        call_command('generate_recommendations', bendras_baltymas, bendras_fenilalaninas)
        
        return JsonResponse({'message': 'Recommendations generated successfully'})
    return JsonResponse({'error': 'Invalid request'}, status=400)


def get_valgiarastis_totals(request):
    selected_date = request.session.get('selectedDate')
    naudotojas = Naudotojai.objects.get(user=request.user)

    if not selected_date:
        return None, None

    valgiarastis = get_object_or_404(Valgiarasciai, fk_Naudotojasid_Naudotojas=naudotojas, data=selected_date)
    valgymai_list = Valgymai.objects.filter(
        fk_Valgiarastisid_Valgiarastis__data=selected_date,
        fk_Valgiarastisid_Valgiarastis__fk_Naudotojasid_Naudotojas=naudotojas
    ).prefetch_related('valgymo_receptas_set').prefetch_related('valgomas_produktas_set')

    total_fenilalaninas = 0
    total_baltymas = 0

    for valgymas in valgymai_list:
        for valgomasreceptas in valgymas.valgymo_receptas_set.all():
            receptas = valgomasreceptas.fk_Receptasid_Receptas
            total_weight = Recepto_produktai.objects.filter(fk_Receptasid_Receptas=receptas).aggregate(total_weight=models.Sum('amount'))['total_weight']
            total_fenilalaninas += round(valgomasreceptas.kiekis / total_weight * Decimal(receptas.fenilalaninas), 1)
            total_baltymas += round(valgomasreceptas.kiekis / total_weight * Decimal(receptas.baltymai), 1)

        for valgomasproduktas in valgymas.valgomas_produktas_set.all():
            total_fenilalaninas += round(valgomasproduktas.kiekis / 100 * Decimal(valgomasproduktas.fk_Produktasid_Produktas.phenylalanine), 1)
            total_baltymas += round(valgomasproduktas.kiekis / 100 * Decimal(valgomasproduktas.fk_Produktasid_Produktas.protein), 1)

    return total_fenilalaninas, total_baltymas


import pandas as pd

import pandas as pd

def rekomendacijos(request):
    # Read the Excel file
    excel_data = pd.ExcelFile('rekomendacijos.xlsx')
    
    # Dictionary to store data from each sheet
    data_dict = {}
    
    # Loop through each sheet and convert the Excel data to a list of dictionaries
    for sheet_name in excel_data.sheet_names:
        if sheet_name == 'Individualios_rek':
            # For Individualios_rek sheet, read data differently
            data = pd.read_excel('rekomendacijos.xlsx', sheet_name=sheet_name)
            data_dict[sheet_name] = data.to_dict(orient='records')
        else:
            # For other sheets, parse normally
            data = excel_data.parse(sheet_name).to_dict(orient='records')
            data_dict[sheet_name] = data


    # Get totals for bendras_fenilalaninas and bendras_baltymas
    bendras_fenilalaninas, bendras_baltymas = get_valgiarastis_totals(request)

    # Pass the data and totals to the template
    context = {
        'data_dict': data_dict,
        'bendras_fenilalaninas': bendras_fenilalaninas,
        'bendras_baltymas': bendras_baltymas,
    }
    return render(request, 'rekomendacijos.html', context)




def valgiarastisAny(request):
    # Extract the clicked date from the URL parameter
    clicked_date = request.GET.get('date', '')  # Default to empty string if not provided
    clicked_date_str = request.GET.get('date', '')
    selected_year = request.GET.get('selected_year', '')
    print ("OOOOOOOOOOOOOOOOO" + selected_year)
    print(clicked_date)
    
    # Split the date string by spaces and take the first element as the year
    clicked_year = clicked_date.split(' ')[0].strip()
    print(clicked_year)

    # Split the date string by spaces and take the third element as the month name
    clicked_month_lithuanian = clicked_date.split(' ')[2].strip()
    print(clicked_month_lithuanian)

    clicked_day = clicked_date.split(' ')[3].strip()
    print(clicked_day)  # Output: 7

    # Map Lithuanian month names to English
    lithuanian_to_english_month = {
        'Sausio': '01',
        'Vasario': '02',
        'Kovo': '03',
        'Balandžio': '04',
        'Gegužės': '05',
        'Birželio': '06',
        'Liepos': '07',
        'Rugpjūčio': '08',
        'Rugsėjo': '09',
        'Spalio': '10',
        'Lapkričio': '11',
        'Gruodžio': '12',
    }

    # Convert Lithuanian month name to numeric representation
    clicked_month = lithuanian_to_english_month.get(clicked_month_lithuanian, '01')  # Default to January if not found
    print('Clicked Month:', clicked_month)

    # Assuming you already have the necessary data to pass to the template
    naudotojas = Naudotojai.objects.get(user=request.user)
    valgiarasciai = Valgiarasciai.objects.filter(fk_Naudotojasid_Naudotojas=naudotojas)
    valgiarasciai_json = serialize('json', valgiarasciai)
    
        # Parse the selected date
    clicked_date = datetime(int(clicked_year), int(clicked_month), int(clicked_day)).date()

    # Query the blood samples filtered by user and sorted by date
    blood_samples = Kraujo_tyrimai.objects.filter(fk_Naudotojasid_Naudotojas=request.user.naudotojai).order_by('data')
    if blood_samples.count() >= 2:
        # Find the closest sample to the selected date
        closest_sample = None
        for sample in reversed(blood_samples):
            sample_date = sample.data
            if sample_date < clicked_date:
                closest_sample = sample
                break
        if closest_sample == None:
            messages.error(request, 'Analizei trūksta duomenų')
            return redirect('kraujo_tyrimai:kraujotyrview', selected_year=selected_year)  # Pass selected 
    else:
          # Print the closest sample
       
        messages.error(request, 'Analizei trūksta duomenų')
        return redirect('kraujo_tyrimai:kraujotyrview', selected_year = selected_year)  # Pass selected year
    
    context = {

        'valgiarasciai_json': valgiarasciai_json,
        'clicked_month': clicked_month,  # Pass the clicked month to the template
        'clicked_date': clicked_date,  # Pass the clicked date to the template
        'clicked_year': clicked_year,
        'clicked_day': clicked_day,
        'closest_sample_data': closest_sample.data
    }

    return render(request, 'ValgiarastisAny.html', context)





def product(request): 
  query = request.GET.get('query')
  category = request.GET.get('category')

  products = Product.objects.all()
  if query:
    products = products.filter(Q(name__icontains=query))
  if category:
    products = products.filter(category=category)
  return render(request, 'Product.html', {'products': products})

def receptai_list(request):
    # Get all recipes
    all_receptai = Receptai.objects.filter(visible=True)
    
    # Get the current user's favorite recipe IDs
    user_favorite_ids = []
    if request.user.is_authenticated:
        current_user = request.user
        naudotojas = Naudotojai.objects.get(user=current_user)
        user_favorite_ids = Megstamiausi_receptai.objects.filter(fk_Naudotojasid_Naudotojas=naudotojas).values_list('fk_Receptasid_Receptas', flat=True)
    
    # Sort recipes based on whether they are in the user's favorites

antife/Mityba/templates/ManoReceptai.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<body>
    <div class="container">
        <h2>Mano Receptai</h2>

        <a href="{% url 'mityba:create_recipe' %}" class="btn btn-primary custom-button">Sukurti naują receptą</a>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Pavadinimas</th>
                    <th>Kalorijos (kcal)</th>
                    <th>Fenilalaninas (mg)</th>
                    <th>Baltymai (g)</th>
                    <th>Veiksmai</th>
                </tr>
            </thead>
            <tbody>
                {% for receptas in manoreceptai_list %}
                    {% if receptas.naudotojo_receptai_set.exists %}
                        <tr>
                            <td class="name-cell" data-toggle="aprasas-{{ forloop.counter }}" data-ingredientai="ingredientai-{{ forloop.counter }}">{{ receptas.pavadinimas }}</td>
                            <td>{{ receptas.kalorijos }}</td>
                            <td>{{ receptas.fenilalaninas }}</td>
                            <td>{{ receptas.baltymai }}</td>
                            <td>
                                <div class="toggle-buttons-container" id="toggle-buttons-container-{{ forloop.counter }}">
                                    <button class="btn btn-secondary toggle-buttons-icon"><i class="fas fa-ellipsis-h"></i></button>
                                    <div class="toggle-buttons">
                                        {% if user.is_authenticated %}
                                            <button class="btn btn-danger remove-recipe" data-id="{{ receptas.id }}">X  </button>
                                            <button class="btn btn-primary edit-button" data-url="{% url 'mityba:edit_recipe' receptas.id %}"><i class="fas fa-pencil-alt"></i></button>
                                            <button class="btn btn-secondary toggle-visibility" data-id="{{ receptas.id }}">
                                                <i class="fas fa-eye{% if receptas.visible %} fa-eye-slash{% endif %}"></i>
                                                <span class="tooltip-text">{% if receptas.visible %}Paslepti{% else %}Atslepti{% endif %}</span>
                                            </button>
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4" id="ingredientai-{{ forloop.counter }}" style="display: none; padding: 10px; background-color: #f2f2f2; border: 1px solid #ddd;">
                                <h3>Ingredientai</h3>
                                <ul>
                                    {% for recepto_produktai in receptas.recepto_produktai_set.all %}
                                        <li>{{ recepto_produktai.fk_Produktasid_Produktas.name }} - {{ recepto_produktai.amount }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4" id="aprasas-{{ forloop.counter }}" style="display: none; padding: 10px; background-color: #f2f2f2; border: 1px solid #ddd;">
                                <h3>Aprasas</h3>
                                <p style="white-space: pre-line;">{{ receptas.aprasas }}</p>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Event listener for clicking on recipe cells
            const nameCells = document.querySelectorAll('.name-cell');
            nameCells.forEach(cell => {
                cell.addEventListener('click', function () {
                    const targetIdAprasas = this.getAttribute('data-toggle');
                    const targetIdIngredientai = this.getAttribute('data-ingredientai');
                    const targetElementAprasas = document.getElementById(targetIdAprasas);
                    const targetElementIngredientai = document.getElementById(targetIdIngredientai);
                    
                    // Toggle the display of both description and ingredients sections
                    if (targetElementAprasas.style.display === 'none') {
                        targetElementAprasas.style.display = '';
                        targetElementIngredientai.style.display = '';
                    } else {
                        targetElementAprasas.style.display = 'none';
                        targetElementIngredientai.style.display = 'none';
                    }
                });
            });

            document.querySelectorAll('.edit-button').forEach(button => {
                button.addEventListener('click', function() {
                    const url = this.getAttribute('data-url');
                    if (url) {
                        window.location.href = url;
                    }
                });
            });

            // Event listener for toggling buttons visibility
            const toggleButtonsIcons = document.querySelectorAll('.toggle-buttons-icon');
            toggleButtonsIcons.forEach(icon => {
                icon.addEventListener('click', function () {
                    const containerId = this.parentNode.id;
                    const buttonsContainer = document.getElementById(containerId);

                    // Toggle the display of buttons
                    const buttons = buttonsContainer.querySelector('.toggle-buttons');
                    buttons.classList.toggle('show');
                });
            });
    
            // Event listener for remove recipe buttons
            const removeRecipeButtons = document.querySelectorAll('.remove-recipe');
            removeRecipeButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const recipeId = this.getAttribute('data-id');
    
                    // Send AJAX request to remove the recipe
                    fetch(`/mityba/receptai_list/${recipeId}/`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                    })
                    .then(response => {
                        if (response.ok) {
                            // If the deletion was successful, remove the corresponding recipe from UI
                            const recipeRow = this.closest('tr');
                            recipeRow.remove();
                            // Display alert for successful removal
                            alert('Receptas buvo sėkmingai pašalintas');
                        } else {
                            console.error('Failed to remove recipe');
                        }
                    })
                    .catch(error => {
                        console.error('Error removing recipe:', error);
                    });
                });
            });
    
            // Event listener for toggling recipe visibility
            const toggleVisibilityButtons = document.querySelectorAll('.toggle-visibility');
            toggleVisibilityButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const recipeId = this.getAttribute('data-id');

                    // Send AJAX request to toggle recipe visibility
                    fetch(`/mityba/receptai_listt/${recipeId}/`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                    })
                    .then(response => {
                        if (response.ok) {
                            // Reload the page after successful toggle
                            location.reload();
                        } else {
                            console.error('Failed to toggle recipe visibility');
                        }
                    })
                    .catch(error => {
                        console.error('Error toggling recipe visibility:', error);
                    });
                });
            });
        });
    </script>
    
    
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-image: url("{% static 'styles/paveiksleliai/R.png' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .styled-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 16px;
            text-align: left;
        }
        .btn {
            height: 38px; /* Set a fixed height for all buttons */
        }

        /* Additional CSS styles */

        .toggle-buttons button {
            margin: 4px;
            height: 38px; /* Ensure all buttons have the same height */
        }

        /* Add this CSS to set the height of the href edit button */
        .toggle-buttons a.btn {
            height: 38px; /* Set the same height as other buttons */
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
            border-bottom: 1px solid #ddd;
            cursor: pointer;
        }

        .styled-table th {
            background-color: #3498db;
            color: #fff;
        }

        .styled-table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .name-cell {
            color: #3498db;
            text-decoration: underline;
            cursor: pointer;
        }
        .tooltip-text {
            visibility: hidden;
            width: 80px;
            background-color: #000;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            bottom: 100%;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0;
            transition: opacity 0.3s;
        }

        .toggle-visibility {
            position: relative;
        }

        .toggle-visibility:hover .tooltip-text {
            visibility: visible;
            opacity: 1;
        }

        .toggle-buttons-container {
            position: relative;
        }

        .toggle-buttons {
            display: none;
            position: absolute;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 4px 0;
            z-index: 1;
            right: 0;
            top: 100%;
        }

        .toggle-buttons.show {
            display: flex;
        }

        .toggle-buttons button {
            margin: 4px;
        }

        .toggle-buttons-icon {
            cursor: pointer;
        }
    </style>
{% endblock %}