antife/Kraujo_tyrimai/urls.py
from django.urls import path
from . import views

app_name = 'kraujo_tyrimai'

urlpatterns = [
    path('', views.kraujotyrview, name='kraujotyrview'),
    path('<int:selected_year>/', views.kraujotyrview, name='kraujotyrview'),
    path('create_kraujo_tyrimas/', views.create_kraujo_tyrimas, name='create_kraujo_tyrimas'),
    path('save_tyrimas/', views.saveTyrimas, name='save_tyrimas'),
    path('delete_tyrimas/', views.deleteTyrimas, name='delete_tyrimas')
    
]

antife/Mityba/urls.py
from django.urls import path
from . import views

app_name = 'Mityba'

urlpatterns = [
    # Define your URL patterns here
    path('product/', views.product, name='product'),
    path('receptai_list/', views.receptai_list, name='receptai_list'),
    path('create_recipe/', views.create_recipe_view, name='create_recipe'),
    path('valgiarastis-analysis/', views.valgiarastisAny, name='valgiarastisAnalysis'),  # Change the URL pattern and view name
    path('valgiarastis/', views.valgiarastis, name='valgiarastis'),  # Move this URL pattern to below the valgiarastisAny pattern
    path('create_valgiarastis/', views.create_valgiarastis, name='create_valgiarastis'),
    path('receptai_list/<int:recipe_id>/', views.remove_recipe_view, name='remove_recipe'),
    path('valgymai/', views.valgymai_open, name='valgymai_open'),
    path('manoreceptai_list/', views.manoreceptai_list, name='manoreceptai_list'),
    path('add_to_favorites/<int:recipe_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('delete_valgomasReceptas/<int:valgymo_receptas_id>/', views.delete_valgomasReceptas, name='delete_valgomasReceptas'),
    path('delete_valgomasProduktas/<int:valgomas_produktas_id>/', views.delete_valgomasProduktas, name='delete_valgomasProduktas'),
    path('add_valgymas/', views.add_new_valgymas, name='add_valgymas'),
    path('saveCopy/', views.saveCopy, name='saveCopy'),
    path('copyValgiarastis/', views.copyValgiarastis, name='copyValgiarastis'),
    path('receptukurimas/', views.create_recipe_view, name='create_recipe'),
    path('panaudotireceptai/', views.panaudotireceptai, name='panaudoti_receptai'),
    path('receptai_list/<int:recipe_id>/edit/', views.edit_recipe, name='edit_recipe'),
    path('rekomendacijos/', views.rekomendacijos, name='rekomendacijos'),
    path('receptai_listt/<int:recipe_id>/', views.toggle_recipe_visibility, name='toggle_recipe_visibility'),
    path('generate-recommendations/', views.generate_recommendations_view, name='generate_recommendations'),
    path('edit_valgomasReceptas/', views.edit_valgomasReceptas, name='edit_valgomasReceptas'),
    path('edit_valgomasProduktas/', views.edit_valgomasProduktas, name='edit_valgomasProduktas'),
]

antife/antife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls"))
]

antife/homepage/urls.py
from django.urls import path, include
from .views import home, login, register, logout_view, loged

urlpatterns = [
   path("", home, name="home"),
   path('login/', login, name='login'),
   path('register/', register, name='register'),
   path('logout/', logout_view, name='logout'),
   path('mityba/', include('Mityba.urls', namespace='mityba')),
   path('forumas/', include('Forumas.urls', namespace='forumas')),
   path('profilis/', include('Profilis.urls', namespace='profilis')), 
   path('kraujo_tyrimai/', include('Kraujo_tyrimai.urls', namespace='kraujo_tyrimai')), 
    path('baseLogged/', loged, name='loged'),
]

antife/Kraujo_tyrimai/models.py
from django.db import models

# Create your models here.

antife/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    calories = models.DecimalField(max_digits=6, decimal_places=2)
    total_fat = models.DecimalField(max_digits=5, decimal_places=2)
    fiber = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    phenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    measure = models.CharField(max_length=255)
    homePhenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    homeWeight = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.CharField(max_length=255)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Naudotojai(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    vardas = models.CharField(max_length=255)
    pavarde = models.CharField(max_length=255)
    telefonas = models.CharField(max_length=255)
    el_pastas = models.CharField(max_length=255)
    gimimo_data = models.DateField()
    level = models.IntegerField()
    last_login = models.DateTimeField(null=True, blank=True)

class Receptai(models.Model):
    kalorijos = models.FloatField(default=0.0)
    pavadinimas = models.CharField(max_length=255)
    fenilalaninas = models.FloatField(default=0.0)
    baltymai = models.FloatField(default=0.0)
    aprasas = models.CharField(max_length=300)
    visible = models.BooleanField(default=True)

class Irasai(models.Model):
    pavadinimas = models.CharField(max_length=255, default="Pavadinimas")
    tekstas = models.CharField(max_length=2555)
    data = models.DateField()
    category = models.CharField(max_length=50,default="Daktarui") # New field for category
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Kraujo_tyrimai(models.Model):
    data = models.DateField()
    fenilalaninas = models.IntegerField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Naudotojo_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Megstamiausi_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Valgiarasciai(models.Model):
    diena = models.IntegerField()
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    data = models.DateField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Komentarai(models.Model):
    tekstas = models.CharField(max_length=255)
    data = models.DateField()
    fk_Irasasid_Irasas = models.ForeignKey(Irasai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)
    likes = models.ManyToManyField(Naudotojai, related_name='liked_comments', blank=True)

class Valgymai(models.Model):
    tipas = models.CharField(max_length=255)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    fk_Valgiarastisid_Valgiarastis = models.ForeignKey(Valgiarasciai, on_delete=models.CASCADE)


class Valgomas_produktas(models.Model):
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Valgymo_receptas(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Recepto_produktai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

antife/Kraujo_tyrimai/templates/Kraujotyr.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
    Kraujo Tyrimai
{% endblock %}

<img src="{% static 'images/good.png' %}" alt="Good">
<img src="{% static 'images/bad.png' %}" alt="Bad">
<img src="{% static 'images/not_found.png' %}" alt="Not Found">

{% block content %}
    <style>
        /* CSS styles inline */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
         
           
           
            background-image: url("{% static 'images/back.png' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
           
           
            background-size: 700px 1050px;
            
            
           
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .form-container {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 350px;
            width: 100%;
            margin: 0 auto 20px;
            box-sizing: border-box;
        }
        label {
            display: inline-block;
            width: 100%;
            margin-bottom: 10px;
            color: #555;
        }
        input[type="date"],
        input[type="number"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            font-size: 14px;
        }
        input[type="submit"] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }
        input[type="submit"]:hover {
            background-color: #45a049;
        }
        .chart-img {
            display: block;
            margin: 20px auto;
            max-width: 100%;
        }
        .error-container {
            margin: 20px auto;
            width: 100%;
            text-align: center;
        }
        .alert {
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .alert-success {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }
        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .tooltip {
            position: relative;
            display: inline-block;
            border-bottom: 1px dotted black;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            width: 120px;
            background-color: black;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            margin-left: -60px;
            opacity: 0;
            transition: opacity 0.3s;
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        .form-wrapper {
            display: flex;
            justify-content: center;
            align-items: flex-start;
            gap: 20px;
        }
        .form-container .input-container {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        select {
            margin-bottom: 25px;
        }
        .form-container:first-child .filtruoti-btn {
            margin-top: 30px;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .checkbox-container {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
        }
        .checkbox-container label {
            width: calc(33.333% - 10px);
            box-sizing: border-box;
        }
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgb(0,0,0);
            background-color: rgba(0,0,0,0.4);
            padding-top: 60px;
        }
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 20%;
        }
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }
        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
        .button-container {
            text-align: center;
            margin-top: 20px;
        }
        .button-container button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            margin: 0 10px;
        }
        .button-container button:hover {
            background-color: #45a049;
        }
        .filter-form-container {
        /*max-width: 380px; */ 
        height: 255px;/* Adjust this value to make the form wider */
    }

    </style>

    <h1>Kraujo tyrimų sekimas</h1>
    
    {% if messages %}
        <div class="error-container">
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="form-wrapper">
        <div class="form-container filter-form-container">
            <form id="filterForm" method="post" action="{% url 'kraujo_tyrimai:kraujotyrview' %}">
                {% csrf_token %}
                <h2>Filtruoti pagal metus</h2>
                <div class="checkbox-container">
                    {% for year in years %}
                        <label for="year{{ year }}">
                            <input type="checkbox" name="year" id="year{{ year }}" value="{{ year }}" {% if year == selected_year %} checked {% endif %}>
                            {{ year }}
                        </label>
                    {% endfor %}
                </div>
            </form>
        </div>
        
        <div class="form-container">
            <form method="post" action="{% url 'kraujo_tyrimai:create_kraujo_tyrimas' %}">
                {% csrf_token %}
                <input type="hidden" name="selected_year" value="{{ selected_year }}">
                <h2>Pridėti kraujo tyrimą</h2>
                <div class="input-container">
                    <label for="id_data">Data:</label>
                    <input type="date" name="data" id="id_data">
                </div>
                <div class="input-container">
                    <label for="id_fenilalaninas">Fenilalaninas µmol/l:</label>
                    <input type="number" name="fenilalaninas" id="id_fenilalaninas">
                </div>
                <input type="submit" value="Pridėti">
            </form>
        </div>
    </div>
    
    {% if chart %}
        {{ chart|safe }}
    {% endif %}

    <div id="popupModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div class="button-container">
                <button id="editBtn">Redaguoti</button>
                <button id="deleteBtn">Ištrinti</button>
                <button id="analyzeBtn">Analizė</button>
            </div>
            <form id="editForm" action="{% url 'kraujo_tyrimai:save_tyrimas' %}" method="post" style="display: none;">
                {% csrf_token %}
                <input type="hidden" id="editSelectedDataPointId" name="selectedDataPointId" value="">
                <input type="hidden" name="selected_year" value="{{ selected_year }}">
                <h3>Redaguoti kraujo tyrimą</h3>
                <div class="input-container">
                    <label for="editDate">Data:</label>
                    <input type="date" id="editDate" name="editedDate">
                </div>
                <div class="input-container">
                    <label for="editFenilalaninas">Fenilalaninas µmol/l:</label>
                    <input type="number" id="editFenilalaninas" name="editedFenilalaninas">
                </div>
                <input type="submit" value="Išsaugoti">
            </form>
        </div>
    </div>
    <form id="deleteForm" action="{% url 'kraujo_tyrimai:delete_tyrimas' %}" method="post" style="display: none;">
        {% csrf_token %}
        <input type="hidden" id="deleteSelectedDataPointId" name="selectedDataPointId" value="">
        <input type="hidden" name="selected_year" value="{{ selected_year }}">
        <input type="submit" value="Delete" id="deleteBtn">
    </form>
    
    <script src="https://mpl-cursors-temmiexue.vercel.app/dist/mplcursors.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const yearCheckboxes = document.querySelectorAll('input[name="year"]');
            const filterForm = document.getElementById('filterForm');

            yearCheckboxes.forEach(function(checkbox) {
                checkbox.addEventListener('change', function(event) {
                    yearCheckboxes.forEach(function(otherCheckbox) {
                        if (otherCheckbox !== event.target) {
                            otherCheckbox.checked = false;
                        }
                    });
                    filterForm.submit();
                });
            });
        });
    </script>
    
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const plotlyGraph = document.querySelector('.plotly-graph-div');

            plotlyGraph.on('plotly_click', function(data) {
                if(data.points.length > 0) {
                    document.getElementById("popupModal").style.display = "block";
                    const clickedData = data.points[0];

                    document.getElementById("editBtn").onclick = function() {
                        const clickedDate = clickedData.x;
                        const phenylalanineAmount = clickedData.y;

                        document.getElementById("editDate").value = clickedDate;
                        document.getElementById("editFenilalaninas").value = phenylalanineAmount;
                        document.getElementById("editSelectedDataPointId").value = clickedDate;
                        document.getElementById("editForm").style.display = "block";
                    };

                    document.getElementById("deleteBtn").onclick = function() {
                        const clickedDate = clickedData.x;
                        document.getElementById("deleteSelectedDataPointId").value = clickedDate;
                        document.getElementById("deleteForm").submit();
                    };

                    document.getElementById("analyzeBtn").onclick = function() {
                        const clickedDate = clickedData.x;
                        const selectedYearCheckbox = document.querySelector('input[name="year"]:checked');
                        const selectedYear = selectedYearCheckbox ? selectedYearCheckbox.value : '';
                        window.location.href = "{% url 'mityba:valgiarastisAnalysis' %}?date=" + encodeURIComponent(clickedDate) + "&selected_year=" + encodeURIComponent(selectedYear);
                    };
                }
            });

            var span = document.getElementsByClassName("close")[0];
            span.onclick = function() {
                document.getElementById("popupModal").style.display = "none";
                document.getElementById("editForm").style.display = "none";
            }
            window.onclick = function(event) {
                var modal = document.getElementById("popupModal");
                if (event.target == modal) {
                    modal.style.display = "none";
                    document.getElementById("editForm").style.display = "none";
                }
            }
        });
    </script>
{% endblock %}