antife/Forumas/urls.py
from django.urls import path, include
from . import views

app_name = 'Forumas'

urlpatterns = [
    path('', views.forumasview, name='forumasview'),
    path('create_topic/', views.create_topic, name='create_topic'),
    path('add_comment/<int:irasas_id>/', views.add_comment, name='add_comment'),
    path('delete_comment/', views.delete_comment, name='delete_comment'),
    path('like_comment/<int:pk>/', views.like_comment, name='like_comment'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

antife/Kraujo_tyrimai/urls.py
from django.urls import path
from . import views

app_name = 'kraujo_tyrimai'

urlpatterns = [
    path('', views.kraujotyrview, name='kraujotyrview'),
    path('<int:selected_year>/', views.kraujotyrview, name='kraujotyrview'),
    path('create_kraujo_tyrimas/', views.create_kraujo_tyrimas, name='create_kraujo_tyrimas'),
    path('save_tyrimas/', views.saveTyrimas, name='save_tyrimas'),
    path('delete_tyrimas/', views.deleteTyrimas, name='delete_tyrimas')
    
]

antife/Mityba/urls.py
from django.urls import path
from . import views

app_name = 'Mityba'

urlpatterns = [
    # Define your URL patterns here
    path('product/', views.product, name='product'),
    path('receptai_list/', views.receptai_list, name='receptai_list'),
    path('create_recipe/', views.create_recipe_view, name='create_recipe'),
    path('valgiarastis-analysis/', views.valgiarastisAny, name='valgiarastisAnalysis'),  # Change the URL pattern and view name
    path('valgiarastis/', views.valgiarastis, name='valgiarastis'),  # Move this URL pattern to below the valgiarastisAny pattern
    path('create_valgiarastis/', views.create_valgiarastis, name='create_valgiarastis'),
    path('receptai_list/<int:recipe_id>/', views.remove_recipe_view, name='remove_recipe'),
    path('valgymai/', views.valgymai_open, name='valgymai_open'),
    path('manoreceptai_list/', views.manoreceptai_list, name='manoreceptai_list'),
    path('add_to_favorites/<int:recipe_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('delete_valgomasReceptas/<int:valgymo_receptas_id>/', views.delete_valgomasReceptas, name='delete_valgomasReceptas'),
    path('delete_valgomasProduktas/<int:valgomas_produktas_id>/', views.delete_valgomasProduktas, name='delete_valgomasProduktas'),
    path('add_valgymas/', views.add_new_valgymas, name='add_valgymas'),
    path('saveCopy/', views.saveCopy, name='saveCopy'),
    path('copyValgiarastis/', views.copyValgiarastis, name='copyValgiarastis'),
    path('receptukurimas/', views.create_recipe_view, name='create_recipe'),
    path('panaudotireceptai/', views.panaudotireceptai, name='panaudoti_receptai'),
    path('receptai_list/<int:recipe_id>/edit/', views.edit_recipe, name='edit_recipe'),
    path('rekomendacijos/', views.rekomendacijos, name='rekomendacijos'),
    path('receptai_listt/<int:recipe_id>/', views.toggle_recipe_visibility, name='toggle_recipe_visibility'),
    path('generate-recommendations/', views.generate_recommendations_view, name='generate_recommendations'),
    path('edit_valgomasReceptas/', views.edit_valgomasReceptas, name='edit_valgomasReceptas'),
    path('edit_valgomasProduktas/', views.edit_valgomasProduktas, name='edit_valgomasProduktas'),
]

antife/Profilis/urls.py
from django.urls import path
from . import views

app_name = 'profilis'

urlpatterns = [
    path('', views.profilisview, name='profilisview'),
    path('save_profile_changes/', views.save_profile_changes, name='save_profile_changes'),
    path('profilis/', views.profilisview, name='profilis'), 
]

antife/antife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls"))
]

antife/homepage/urls.py
from django.urls import path, include
from .views import home, login, register, logout_view, loged

urlpatterns = [
   path("", home, name="home"),
   path('login/', login, name='login'),
   path('register/', register, name='register'),
   path('logout/', logout_view, name='logout'),
   path('mityba/', include('Mityba.urls', namespace='mityba')),
   path('forumas/', include('Forumas.urls', namespace='forumas')),
   path('profilis/', include('Profilis.urls', namespace='profilis')), 
   path('kraujo_tyrimai/', include('Kraujo_tyrimai.urls', namespace='kraujo_tyrimai')), 
    path('baseLogged/', loged, name='loged'),
]

antife/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    calories = models.DecimalField(max_digits=6, decimal_places=2)
    total_fat = models.DecimalField(max_digits=5, decimal_places=2)
    fiber = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    phenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    measure = models.CharField(max_length=255)
    homePhenylalanine = models.DecimalField(max_digits=6, decimal_places=2)
    homeWeight = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.CharField(max_length=255)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Naudotojai(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    vardas = models.CharField(max_length=255)
    pavarde = models.CharField(max_length=255)
    telefonas = models.CharField(max_length=255)
    el_pastas = models.CharField(max_length=255)
    gimimo_data = models.DateField()
    level = models.IntegerField()
    last_login = models.DateTimeField(null=True, blank=True)

class Receptai(models.Model):
    kalorijos = models.FloatField(default=0.0)
    pavadinimas = models.CharField(max_length=255)
    fenilalaninas = models.FloatField(default=0.0)
    baltymai = models.FloatField(default=0.0)
    aprasas = models.CharField(max_length=300)
    visible = models.BooleanField(default=True)

class Irasai(models.Model):
    pavadinimas = models.CharField(max_length=255, default="Pavadinimas")
    tekstas = models.CharField(max_length=2555)
    data = models.DateField()
    category = models.CharField(max_length=50,default="Daktarui") # New field for category
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Kraujo_tyrimai(models.Model):
    data = models.DateField()
    fenilalaninas = models.IntegerField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Naudotojo_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Megstamiausi_receptai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Valgiarasciai(models.Model):
    diena = models.IntegerField()
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    data = models.DateField()
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)

class Komentarai(models.Model):
    tekstas = models.CharField(max_length=255)
    data = models.DateField()
    fk_Irasasid_Irasas = models.ForeignKey(Irasai, on_delete=models.CASCADE)
    fk_Naudotojasid_Naudotojas = models.ForeignKey(Naudotojai, on_delete=models.CASCADE)
    likes = models.ManyToManyField(Naudotojai, related_name='liked_comments', blank=True)

class Valgymai(models.Model):
    tipas = models.CharField(max_length=255)
    bendras_baltymas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    bendras_fenilalaninas = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    fk_Valgiarastisid_Valgiarastis = models.ForeignKey(Valgiarasciai, on_delete=models.CASCADE)


class Valgomas_produktas(models.Model):
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Valgymo_receptas(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Valgymasid_Valgymas = models.ForeignKey(Valgymai, on_delete=models.CASCADE)
    kiekis = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

class Recepto_produktai(models.Model):
    fk_Receptasid_Receptas = models.ForeignKey(Receptai, on_delete=models.CASCADE)
    fk_Produktasid_Produktas = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

antife/homepage/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Naudotojai
from django.db.models import Q
from django.contrib.auth import authenticate
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.sessions.models import Session
import re

def home(request):
    return render(request, "home.html")

def loged(request):
    return render(request, "baseLogged.html")

from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User


from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Naudotojai
import re

from datetime import datetime

def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        name = request.POST.get('name')
        lastName = request.POST.get('lastName')
        phoneNumber = request.POST.get('phoneNumber')
        birthday = request.POST.get('birthday')
        password = request.POST.get('password')
        if User.objects.filter(username=username):
            messages.error(request, 'Šis slapyvardis jau užimtas!')
            return render (request, 'register.html')
        # Validate email format using regular expression
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email) or not email.endswith('@gmail.com'):
            messages.error(request, 'Neteisingai įvestas elektronins paštas. Įveskite teisingą.')
        elif User.objects.filter(email=email).exists():
            # Set the message if the email already exists
            messages.error(request, 'Šis elektroninis paštas jau užimtas.')
        elif not re.match(r"\+370\d{8}", phoneNumber):
            # Validate phone number format
            # ^\+370 - starts with +370
            # \d{8}$ - followed by exactly 8 digits
            messages.error(request, 'Neteisingai įvestas telefono numeris. Įveskite per naują' )
        else:
            # Validate birthdate format and range
            try:
                birthdate_obj = datetime.strptime(birthday, '%Y-%m-%d').date()
                today = datetime.now().date()
                if birthdate_obj >= today:
                    raise ValueError  # Birthdate should be in the past
            except ValueError:
                messages.error(request, 'Neteisinga gimimo data. Pasirinkite dar kartą.')
                return render(request, 'register.html')
            
            # Create a new user account
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()

            # Hash the password
            hashed_password = make_password(password)
            
            # Save the user profile data to the database
            new_user_profile = Naudotojai(
                user=user,  # Associate the profile with the newly created user
                vardas=name,
                telefonas=phoneNumber,
                pavarde=lastName,
                gimimo_data=birthdate_obj,
                level=0  # Set default level or adjust as needed
            )  
            new_user_profile.save() 

            messages.success(request, f'Registracija sėkminga. Gali bandyt prisijungt!')
            return redirect('/login')  # Change 'home' to the name of your homepage URL pattern
    
    return render(request, 'register.html')





from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as django_login

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
            
        if user is not None and user.is_active:
            django_login(request, user)
            messages.success(request, f"Sėkmingai prisijungėte! Sveiki, {username}")
            return render(request, 'baseLogged.html')  # Redirect to the main forum page
        else:
            messages.error(request, "Neteisingi prisijungimo duomenys. Bandyk dar kartą.")
    
    return render(request, 'login.html')






from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_view(request):
    logout(request)
    request.session.flush()  # Clear all session data
    return redirect('/')  # Redirect to the homepage or any other desired URL

antife/homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Django App
      {% load static %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <style>
    /* Custom Button Style */
    button.custom-button {
      background-color: #007bff; /* Blue */
      border: none;
      color: white;
      padding: 10px 20px;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
    }
    
    /* Hover effect */
    button.custom-button:hover {
      background-color: #0056b3; /* Darker Blue */
    }
    
    /* Profile image style */
    .navbar .profile-img {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      object-fit: cover;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">ANTIFE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'forumas:forumasview' %}">Forumas</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'kraujo_tyrimai:kraujotyrview' %}">Kraujo tyrimai</a>
        </li>
        {% endif %}
        <!-- Mityba dropdown menu with Produktai and Receptai options -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="mitybaDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mityba
          </a>
          <div class="dropdown-menu" aria-labelledby="mitybaDropdown">
            <a class="dropdown-item" href="{% url 'mityba:product' %}">Produktai</a>
            <a class="dropdown-item" href="{% url 'mityba:receptai_list' %}">Receptai</a>
            {% if request.user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'mityba:valgiarastis' %}">Valgiaraštis</a>
            <a class="dropdown-item" href="{% url 'mityba:manoreceptai_list' %}">Mano Receptai</a>
            {% endif %}
          </div>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'profilis:profilisview' %}">
            <img src="{% static 'images/profile.jpg' %}" alt="Profile" class="profile-img">
          </a>
        </li>
        {% endif %}
      </ul>
      {% if request.user.is_authenticated %}
      <button type="button" class="btn btn-primary custom-button" onclick="Loguot()">Atsijungti</button>
      {% else %}
      <button type="button" class="btn btn-primary custom-button" onclick="openLogin()">Prisijungti</button>
      <button type="button" class="btn btn-primary custom-button" onclick="openRegister()">Registruotis</button>
      {% endif %}
    </div>
  </nav>
  <div class="container">{% block content %} {% endblock %}</div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <script>
    function openLogin() {
      // Redirect to the login page
      window.open("{% url 'login' %}", "_self");
    }
  
    function openRegister() {
      // Redirect to the register page
      window.open("{% url 'register' %}", "_self");
    }

    function Loguot() {
      // Atjungiam nuo sesijos ir perkraunam
      window.open("{% url 'logout' %}", "_self");
    }
  </script>
</body>
</html>

antife/homepage/templates/baseLogged.html
{% extends "base.html" %}
{% block title %} Home Page {% endblock %}
{% block content %}

{% load static %}

<style>
    body {
        background-image: url("{% static 'images/depositphotos_207250452-stock-photo-top-view-food-composition-various.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>

<style>
    h1 {
        font-size: 4rem;
        font-weight: bold;
        background: linear-gradient(to right, #ff9966, #ff5e62);
        background-clip: text;
        -webkit-background-clip: text;
        color: transparent;
        transition: all 0.5s ease;
        padding: 20px; /* Add padding to h1 */
    }

    h1:hover {
        transform: rotate(-2deg);
    }
</style>
<h1 style="text-align: center;">Sveiki atvykę į ANTIFE!</h1>
<h2 style="text-align: center;">Interaktyvus dietos asistentas specialiai fenilketonurijos pacientams.</h2>
<h3 style="text-align: center"> Tai aplinka, kuri padeda spręsti kasdienes šios ligos sukeliamas problemas! </h3>


{% endblock %}

antife/homepage/templates/home.html
{% extends "base.html" %}
{% block title %} Home Page {% endblock %}
{% block content %}

{% load static %}

<style>
    body {
        background-image: url("{% static 'images/depositphotos_207250452-stock-photo-top-view-food-composition-various.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>

<style>
    h1 {
        font-size: 4rem;
        font-weight: bold;
        background: linear-gradient(to right, #ff9966, #ff5e62);
        background-clip: text;
        -webkit-background-clip: text;
        color: transparent;
        transition: all 0.5s ease;
        padding: 20px; /* Add padding to h1 */
    }

    h1:hover {
        transform: rotate(-2deg);
    }
</style>
<h1 style="text-align: center;">Sveiki atvykę į ANTIFE!</h1>
<h2 style="text-align: center;">Interaktyvus dietos asistentas specialiai fenilketonurijos pacientams.</h2>
<h3 style="text-align: center"> Tai aplinka, kuri padeda spręsti kasdienes šios ligos sukeliamas problemas! </h3>


{% endblock %}

antife/homepage/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Django App
    {% endblock %}
  </title>
 
  
  
  <link rel="stylesheet" type="text/css" href="{% static 'styles/errors.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'styles/login.css' %}"> 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  
</head>
<body>
  
  <div class="wrapper">
    <form action="" method="post">
        {% csrf_token %}
        <h1> Prisijungimo forma </h1>
        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-error{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="input-box">
          <input type="text" name="username" placeholder="Slapyvardis" required>
          <i class='bx bxs-user'></i>
        </div>

        <div class="input-box">
          <input type="password" name="password" placeholder="Slaptažodis" required>
          <i class='bx bxs-lock-alt'></i>
        </div>
        <div class="remember-forgot">
        </div>
        <button type="submit" class="btn btn-primary custom-button"> Prisijungti </button>
        <div class="register-link">
          <p> Neturi paskyros?<a href="/register"> Užsiregistruok!</a></p>
        </div>
    </form>
  </div>
  
  
</body>
</html>

antife/homepage/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Django App
    {% endblock %}
  </title>
  
  <link rel="stylesheet" type="text/css" href="{% static 'styles/register.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'styles/errors.css' %}">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  
</head>
<body>
  <div class="wrapper">
    <form action="/register/" method="post">
        {% csrf_token %}
        <h1> Registracijos forma </h1>
        <!-- register.html -->
        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-error{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="input-box">
          <input type="text" name="email" placeholder="Elektroninis paštas" required>
          <i class='bx bx-envelope' ></i>
        </div>
        <div class="input-box">
          <input type="text" name="username" placeholder="Slapyvardis" required>
          <i class='bx bxs-mask' ></i>
        </div>

        <div class="input-box">
          <input type="text" name="name" placeholder="Vardas" required>
          <i class='bx bxs-user'></i>
        </div>

        <div class="input-box">
          <input type="text" name="lastName" placeholder="Pavardė" required>
          <i class='bx bxs-user'></i>
        </div>
        <div class="input-box">
          <input type="text" name="phoneNumber" placeholder="Telefono numeris (+370)" required>
          <i class='bx bxs-phone'></i>
        </div>
        <div class="input-box">
          <input type="date" name="birthday" placeholder="Gimimo data" required>
          <i class='bx bx-calendar' ></i>
        </div>

        <div class="input-box">
          <input type="password" name="password" placeholder="Slaptažodis" required>
          <i class='bx bxs-lock-alt'></i>
        </div>
        <div class="input-box">
            <input type="password" name="repeat_password" placeholder="Pakartoti slaptažodė" required>
            <i class='bx bxs-lock-alt'></i>
          </div>
        
        <div class="login-link">
          <p> Turi paskyrą? <a href="{% url 'login' %}"> Prisijungti! </a></p>
        </div>
       
        <button type="submit" class="btn btn-primary custom-button"> Registruotis </button>
        
    </form>
  </div>
  
</body>
</html>